env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
  # - plugin:prettier/recommended
  # - plugin:jest/recommended
parserOptions:
  ecmaVersion: latest
rules:
  curly: 'off'
  max-len: 'off'
  operator-linebreak: 'off'
  import/no-unresolved: 'error'
  import/prefer-default-export: 'off'
  nonblock-statement-body-position: 'off'
  no-use-before-define: 'off'
  no-underscore-dangle: 'off'
  no-console: 'off'
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_

# plugins:
#   - jest