

service: search-service
frameworkVersion: '3'
plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  environment:
    APP_ENV: dev
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    ACCOUNT_ID: "#{AWS::AccountId}"
    TEXT_EXTRACTED_NOTIFICATION_SNS: AmazonTextract-${opt:stage}-text-extracted-notification
    PUBLISH_TO_SNS_ROLE: PublishToSNS


resources:
  Resources:
    PublishToSNS:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:provider.environment.PUBLISH_TO_SNS_ROLE}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - textract.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: policyForSNSPublication
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: "*"
    GetLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: GetLambdaRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - s3:ListBucket
                    - s3:GetObject
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - textract:AnalyzeDocument
                    - textract:StartDocumentAnalysis
                  Resource: "*"

functions:
  search:
    handler: packages/search/lambda/get.handler
    timeout: 120
    role: GetLambdaRole
    events:
      - http:
         path: /search
         method: get
         cors: false
  extractText:
    handler: packages/extract-text/lambda/extract.handler
    timeout: 900
    events:
      - sns: ${self:provider.environment.TEXT_EXTRACTED_NOTIFICATION_SNS}



            
